title: "Denis Lysenko"
description: "Personal blog with interesting IT and life stories."
url: "http://lysenkooo.ru"
paginate: 10
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
