title: "Denis Lysenko"
description: "Personal blog about IT"
url: "http://lysenkooo.ru"
paginate: 10
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
